# Imports

In [4]:
from numpy.random import seed
seed(888)
import tensorflow as tf
tf.random.set_seed(888)
import os
import numpy as np
from time import strftime
from PIL import Image

# Constants

In [56]:
X_TRAIN_PATH = 'MNIST/digit_xtrain.csv'
X_TEST_PATH = 'MNIST/digit_xtest.csv'
Y_TRAIN_PATH = 'MNIST/digit_ytrain.csv'
Y_TEST_PATH = 'MNIST/digit_ytest.csv'

LOGGING_PATH = 'tensorboard_mnist_digit_logs/'

NR_CLASSES = 10
VALIDATION_SIZE = 10000
IMAGE_WIDTH = 28
IMAGE_HEIGHT = 28
CHANNELS = 1
TOTAL_INPUTS = IMAGE_WIDTH*IMAGE_HEIGHT*CHANNELS

# Get the Data

In [7]:
%%time

y_train_all = np.loadtxt(Y_TRAIN_PATH, delimiter=',', dtype=int)

Wall time: 11.3 ms


In [8]:
y_train_all.shape

(60000,)

In [9]:
y_test = np.loadtxt(Y_TEST_PATH, delimiter=',', dtype=int)

In [10]:
%%time

x_train_all = np.loadtxt(X_TRAIN_PATH, delimiter=',', dtype=int)

Wall time: 4.58 s


In [11]:
%%time

x_test = np.loadtxt(X_TEST_PATH, delimiter=',', dtype=int)

Wall time: 736 ms


# Explore

In [12]:
x_train_all.shape

(60000, 784)

In [13]:
x_train_all[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [14]:
y_train_all.shape

(60000,)

In [15]:
x_test.shape

(10000, 784)

In [16]:
y_train_all[:5]

array([5, 0, 4, 1, 9])

# Data Preprocessing

In [17]:
# Re-scale
x_train_all, x_test = x_train_all / 255.0, x_test / 255.0

#### Convert target values to one-hot encoding

In [24]:
values = y_train_all[:5]
values

array([5, 0, 4, 1, 9])

In [25]:
np.eye(10)[values]
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
np.eye(10)[2]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
values[4]

9

In [29]:
y_train_all = np.eye(NR_CLASSES)[y_train_all]

In [30]:
y_train_all.shape

(60000, 10)

In [31]:
y_test = np.eye(NR_CLASSES)[y_test]
y_test.shape

(10000, 10)

### Create validation dataset from training data

**Challenge:** Split the training dataset into a smaller training dataset and a validation dataset for the features and the labels. Create four arrays: ```x_val```, ```y_val```, ```x_train```, and ```y_train``` from ```x_train_all``` and ```y_train_all```. Use the validation size of 10,000. 

In [32]:
x_val = x_train_all[:VALIDATION_SIZE]
y_val = y_train_all[:VALIDATION_SIZE]

In [33]:
x_train = x_train_all[VALIDATION_SIZE:]
y_train = y_train_all[VALIDATION_SIZE:]

In [34]:
x_train.shape

(50000, 784)

In [35]:
x_val.shape

(10000, 784)

# Setup Tensorflow Graph

In [ ]:
# NR_CLASSES = 10
# VALIDATION_SIZE = 10000
# IMAGE_WIDTH = 28
# IMAGE_HEIGHT = 28
# CHANNELS = 1
# TOTAL_INPUTS = IMAGE_WIDTH*IMAGE_HEIGHT*CHANNELS

# X = tf.compat.v1.placeholder(tf.float32, shape=[None, TOTAL_INPUTS], name='X')
# Y = tf.compat.v1.placeholder(tf.float32, shape=[None, NR_CLASSES], name='labels')

# nr_epochs = 50
# learning_rate = 1e-3

# n_hidden1 = 512
# n_hidden2 = 64


# def setup_layer(input_tensor, weight_dim, bias_dim, name):
    
#     with tf.name_scope(name):
#         initial_w = tf.truncated_normal(shape=weight_dim, stddev=0.1, seed=42)
#         w = tf.Variable(initial_value=initial_w, name='W')

#         initial_b = tf.constant(value=0.0, shape=bias_dim)
#         b = tf.Variable(initial_value=initial_b, name='B')

#         layer_in = tf.matmul(input_tensor, w) + b
        
#         if name=='out':
#             layer_out = tf.nn.softmax(layer_in)
#         else:
#             layer_out = tf.nn.relu(layer_in)
        
#         tf.summary.histogram('weights', w)
#         tf.summary.histogram('biases', b)
        
#         return layer_out
    
    
# layer_1 = setup_layer(X, weight_dim=[TOTAL_INPUTS, n_hidden1], 
#                       bias_dim=[n_hidden1], name='layer_1')

# layer_drop = tf.nn.dropout(layer_1, keep_prob=0.8, name='dropout_layer')

# layer_2 = setup_layer(layer_drop, weight_dim=[n_hidden1, n_hidden2], 
#                       bias_dim=[n_hidden2], name='layer_2')

# output = setup_layer(layer_2, weight_dim=[n_hidden2, NR_CLASSES], 
#                       bias_dim=[NR_CLASSES], name='out')

# model_name = f'{n_hidden1}-DO-{n_hidden2} LR{learning_rate} E{nr_epochs}'

# # Folder for Tensorboard

# folder_name = f'{model_name} at {strftime("%H:%M")}'
# directory = os.path.join(LOGGING_PATH, folder_name)

# try:
#     os.makedirs(directory)
# except OSError as exception:
#     print(exception.strerror)
# else:
#     print('Successfully created directories!')
    

# with tf.name_scope('loss_calc'):
#     loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=Y, logits=output))
    
# with tf.name_scope('optimizer'):
#     optimizer = tf.train.AdamOptimizer(learning_rate)
#     train_step = optimizer.minimize(loss)    
    
# with tf.name_scope('accuracy_calc'):
#     correct_pred = tf.equal(tf.argmax(output, axis=1), tf.argmax(Y, axis=1))
#     accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))
    
# with tf.name_scope('performance'):
#     tf.summary.scalar('accuracy', accuracy)
#     tf.summary.scalar('cost', loss)
    
# with tf.name_scope('show_image'):
#     x_image = tf.reshape(X, [-1, 28, 28, 1])
#     tf.summary.image('image_input', x_image, max_outputs=4)

### Neural Network Architecture

#### Hyperparameters

In [38]:
# Model without dropout
# layer_1 = setup_layer(X, weight_dim=[TOTAL_INPUTS, n_hidden1], 
#                       bias_dim=[n_hidden1], name='layer_1')

# layer_2 = setup_layer(layer_1, weight_dim=[n_hidden1, n_hidden2], 
#                       bias_dim=[n_hidden2], name='layer_2')

# output = setup_layer(layer_2, weight_dim=[n_hidden2, NR_CLASSES], 
#                       bias_dim=[NR_CLASSES], name='out')

# model_name = f'{n_hidden1}-{n_hidden2} LR{learning_rate} E{nr_epochs}'

In [54]:
# layer_1 = setup_layer(X, weight_dim=[TOTAL_INPUTS, n_hidden1], 
#                       bias_dim=[n_hidden1], name='layer_1')

# layer_drop = tf.nn.dropout(layer_1, keep_prob=0.8, name='dropout_layer')

# layer_2 = setup_layer(layer_drop, weight_dim=[n_hidden1, n_hidden2], 
#                       bias_dim=[n_hidden2], name='layer_2')

# output = setup_layer(layer_2, weight_dim=[n_hidden2, NR_CLASSES], 
#                       bias_dim=[NR_CLASSES], name='out')

# model_name = f'{n_hidden1}-DO-{n_hidden2} LR{learning_rate} E{nr_epochs}'

In [45]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout

model = Sequential([
    # First hidden layer with 512 units and ReLU activation
    Dense(n_hidden1, activation='relu', input_shape=(TOTAL_INPUTS,), name='layer_1'),
    
    # Dropout layer with 20% drop rate
    Dropout(rate=0.2, name='dropout_layer'),
    
    # Second hidden layer with 64 units and ReLU activation
    Dense(n_hidden2, activation='relu', name='layer_2'),
    
    # Output layer with NR_CLASSES units and softmax activation
    Dense(NR_CLASSES, activation='softmax', name='out')
])

# Tensorboard Setup

In [ ]:
# Folder for Tensorboard

# folder_name = f'{model_name} at {strftime("%H:%M")}'
# directory = os.path.join(LOGGING_PATH, folder_name)

# try:
#     os.makedirs(directory)
# except OSError as exception:
#     print(exception.strerror)
# else:
#     print('Successfully created directories!')

In [58]:
model_name = f'{n_hidden1}-DO-{n_hidden2} LR{learning_rate} E{nr_epochs}'
folder_name = f'{model_name} at {strftime("%H_%M")}'
directory = os.path.join(LOGGING_PATH, folder_name)
os.makedirs(directory, exist_ok=True)

# Loss, Optimisation & Metrics

In [ ]:
# # Defining Loss Function
# with tf.name_scope('loss_calc'):
#     loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=Y, logits=output))

# # Defining Optimizer
# with tf.name_scope('optimizer'):
#     optimizer = tf.train.AdamOptimizer(learning_rate)
#     train_step = optimizer.minimize(loss)
    
# # Accuracy Metric
# with tf.name_scope('accuracy_calc'):
#     correct_pred = tf.equal(tf.argmax(output, axis=1), tf.argmax(Y, axis=1))
#     accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))
    
# with tf.name_scope('performance'):
#     tf.summary.scalar('accuracy', accuracy)
#     tf.summary.scalar('cost', loss)
    
# # Check Input Images in Tensorboard
# with tf.name_scope('show_image'):
#     x_image = tf.reshape(X, [-1, 28, 28, 1])
#     tf.summary.image('image_input', x_image, max_outputs=4)

In [59]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate),
              loss='categorical_crossentropy',
              metrics=['accuracy'])


# Run Session

In [ ]:
# sess = tf.Session()

# #Setup Filewriter and Merge Summaries
# merged_summary = tf.summary.merge_all()

# train_writer = tf.summary.FileWriter(directory + '/train')
# train_writer.add_graph(sess.graph)

# validation_writer = tf.summary.FileWriter(directory + '/validation')

# #initialise the variables
# init = tf.global_variables_initializer()
# sess.run(init)

# #batching the data
# size_of_batch = 1000

# num_examples = y_train.shape[0]
# nr_iterations = int(num_examples/size_of_batch)

# index_in_epoch = 0


# def next_batch(batch_size, data, labels):
    
#     global num_examples
#     global index_in_epoch
    
#     start = index_in_epoch
#     index_in_epoch += batch_size
    
#     if index_in_epoch > num_examples:
#         start = 0
#         index_in_epoch = batch_size
    
#     end = index_in_epoch
    
#     return data[start:end], labels[start:end]

# # training loop
# for epoch in range(nr_epochs):
    
#     # ============= Training Dataset =========
#     for i in range(nr_iterations):
        
#         batch_x, batch_y = next_batch(batch_size=size_of_batch, data=x_train, labels=y_train)
        
#         feed_dictionary = {X:batch_x, Y:batch_y}
        
#         sess.run(train_step, feed_dict=feed_dictionary)
        
    
#     s, batch_accuracy = sess.run(fetches=[merged_summary, accuracy], feed_dict=feed_dictionary)
        
#     train_writer.add_summary(s, epoch)
    
#     print(f'Epoch {epoch} \t| Training Accuracy = {batch_accuracy}')
    
#     # ================== Validation ======================
    
#     summary = sess.run(fetches=merged_summary, feed_dict={X:x_val, Y:y_val})
#     validation_writer.add_summary(summary, epoch)

# print('Done training!')


In [60]:
from tensorflow.keras.callbacks import TensorBoard

# Define TensorBoard callback
tensorboard_callback = TensorBoard(log_dir=directory, histogram_freq=1)

# Defining the batch size
size_of_batch = 1000

# Fit the model using the training data
history = model.fit(
    x_train, y_train,
    batch_size=size_of_batch,
    epochs=nr_epochs,
    verbose=1,
    validation_data=(x_val, y_val),
    callbacks=[tensorboard_callback]
)

print('Done training!')

Epoch 1/50
50/50 [==============================] - 8s 90ms/step - loss: 0.6251 - accuracy: 0.8206 - val_loss: 0.2526 - val_accuracy: 0.9286
Epoch 2/50
50/50 [==============================] - 4s 72ms/step - loss: 0.2286 - accuracy: 0.9324 - val_loss: 0.1782 - val_accuracy: 0.9484
Epoch 3/50
50/50 [==============================] - 2s 46ms/step - loss: 0.1646 - accuracy: 0.9520 - val_loss: 0.1435 - val_accuracy: 0.9591
Epoch 4/50
50/50 [==============================] - 2s 46ms/step - loss: 0.1297 - accuracy: 0.9626 - val_loss: 0.1232 - val_accuracy: 0.9640
Epoch 5/50
50/50 [==============================] - 2s 45ms/step - loss: 0.1059 - accuracy: 0.9691 - val_loss: 0.1053 - val_accuracy: 0.9694
Epoch 6/50
50/50 [==============================] - 2s 45ms/step - loss: 0.0885 - accuracy: 0.9734 - val_loss: 0.0994 - val_accuracy: 0.9708
Epoch 7/50
50/50 [==============================] - 2s 45ms/step - loss: 0.0751 - accuracy: 0.9777 - val_loss: 0.0885 - val_accuracy: 0.9730
Epoch 8/50
50

# Make a Prediction

In [ ]:
img = Image.open('MNIST/test_img.png')
img

In [ ]:
# img = Image.open('MNIST/test_img.png')
# bw = img.convert('L')
# img_array = np.invert(bw)
# test_img = img_array.ravel()
# prediction = sess.run(fetches=tf.argmax(output, axis=1), feed_dict={X:[test_img]})
# print(f'Prediction for test image is {prediction}')

In [61]:
img = Image.open('MNIST/test_img.png')
bw = img.convert('L')
img_array = np.invert(bw)
test_img = img_array.ravel().reshape(1, -1) # Make sure to reshape the image to match the input shape
prediction = model.predict(test_img)
predicted_class = np.argmax(prediction, axis=1)

print(f'Prediction for test image is {predicted_class}')

1/1 [==============================] - 3s 3s/step
Prediction for test image is [2]


In [64]:
%load_ext tensorboard
%tensorboard --logdir=directory

# Testing and Evaluation

**Challenge:** Calculate the accuracy over the test dataset (```x_test``` and ```y_test```). Use your knowledge of running a session to get the accuracy. Display the accuracy as a percentage rounded to two decimal numbers. 

In [62]:
# test_accuracy = sess.run(fetches=accuracy, feed_dict={X:x_test, Y:y_test})
# print(f'Accuracy on test set is {test_accuracy:0.2%}')

test_loss, test_accuracy = model.evaluate(x_test, y_test)
print(f'Accuracy on test set is {test_accuracy:0.2%}')

313/313 [==============================] - 4s 2ms/step - loss: 0.0743 - accuracy: 0.9820
Accuracy on test set is 98.20%


# Reset for the Next Run

In [ ]:
# train_writer.close()
# validation_writer.close()
# sess.close()
# tf.reset_default_graph()

# Code for 1st Part of Module

In [ ]:
# with tf.name_scope('hidden_1'):

#     initial_w1 = tf.truncated_normal(shape=[TOTAL_INPUTS, n_hidden1], stddev=0.1, seed=42)
#     w1 = tf.Variable(initial_value=initial_w1, name='w1')

#     initial_b1 = tf.constant(value=0.0, shape=[n_hidden1])
#     b1 = tf.Variable(initial_value=initial_b1, name='b1')

#     layer1_in = tf.matmul(X, w1) + b1

#     layer1_out = tf.nn.relu(layer1_in)

**Challenge:** Set up the second hindden layer. This layer has 64 neurons and needs to work off the output of the first hidden layer (see above). Then setup the output layer. Remember, the output layer will use the softmax activation function. 

In [ ]:
# with tf.name_scope('hidden_2'):

#     initial_w2 = tf.truncated_normal(shape=[n_hidden1, n_hidden2], stddev=0.1, seed=42)
#     w2 = tf.Variable(initial_value=initial_w2, name='w2')

#     initial_b2 = tf.constant(value=0.0, shape=[n_hidden2])
#     b2 = tf.Variable(initial_value=initial_b2, name='b2')

#     layer2_in = tf.matmul(layer1_out, w2) + b2
#     layer2_out = tf.nn.relu(layer2_in)

In [ ]:
# with tf.name_scope('output_layer'):

#     initial_w3 = tf.truncated_normal(shape=[n_hidden2, NR_CLASSES], stddev=0.1, seed=42)
#     w3 = tf.Variable(initial_value=initial_w3, name='w3')

#     initial_b3 = tf.constant(value=0.0, shape=[NR_CLASSES])
#     b3 = tf.Variable(initial_value=initial_b3, name='b3')

#     layer3_in = tf.matmul(layer2_out, w3) + b3
#     output = tf.nn.softmax(layer3_in)

In [ ]:
# b3.eval(sess)